### PR TITLE
Make the mod for 1.17.1

### PR DESCRIPTION
**Pull request by PixelFederico**
The version of minecraft 1.17 is full of bugs and the majority of people can't start the game because the language of the system isn't english

### CODE REVIEW

**Comment by carl-vbn** [comment]
Could you check if recording with `/vxanim record` still works in 1.17.1? I remember encountering problems with the screenshotting system when I tried updating to 1.17.1, thanks!

**Comment by PixelFederico** [comment]
I don't know if you did something wrong but everything work

**Comment by carl-vbn** [comment]
Alright, your last PR (#4) did fix the screenshot problem. However, it still didn't build on my side until I updated FabricAPI from 0.36.0 to 0.40.1. Is it okay for you if I merge all these changes myself as part of an updated version I'm working on and credit you for the bug fix, instead of merging both of your pull requests separately?

**Comment by PixelFederico** [comment]
I'm sorry for the response time, of course you can. Thanks

**Comment by carl-vbn** [comment]
Perfect, thank you!

**Pull request closed without merging**
